title: "usedare"
description: "Cosmic portfolio and blog"
baseurl: ""
url: "https://usedare.github.io"

plugins:
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown
permalink: /blog/:categories/:year/:month/:day/:title/

navigation:
  - title: Home
    url: /#hero
  - title: About
    url: /#about
  - title: Projects
    url: /#projects
  - title: Blog
    url: /#blog
  - title: Comments
    url: /#comments

exclude:
  - Dockerfile
  - docker-compose.yml
  - Gemfile.lock
  - README.md
  - vendor/
